apiVersion: v1
kind: Service
metadata:
  name: anvil-service
  labels:
    app: anvil
spec:
  type: NodePort
  selector:
    app: anvil
  ports:
  - protocol: TCP
    port: 8545         # Service port (used inside the cluster)
    targetPort: 8545   # Port the container listens on
    nodePort: 30000    # External port (must be in the range 30000-32767)

